### ISSUE TITLE
Claim Woocommerce_plugin

### ISSUE THREAD

**Issue by conorseed** [ProtonProtocol/bounties#2]
# Claim for Bounty: WordPress/WooCommerce Plugin for WebAuth Wallet and Proton Blockchain xTokens

I would love to contribute working on this - as owner of Coruscate Digital and Lead Developer at Tailgunner both in New Zealand, I have 10+ years experience developing with Wordpress & Woocommerce, and still actively develop sites using Wordpress. I also have great experience of Proton development being a frontend developer for FreeDAO - working on the [Freeos dApp](https://app.freeos.io/), as well as [The DAOScape](https://ezoku-2iaaa-aaaad-qdrqa-cai.ic.fleek.co/). I'm also very slowly chipping away at a personal project: [ProtonPlay](https://protonplay.fun/).

## Concept

- This would be an open source payment gateway plugin for Woocommerce, with its own settings under Woocommerce -> Settings -> Payments.
- The admin would be able to set the account to which payments would be made, choose which xTokens they will allow for payment, and allow for testing on Testnet. 
- On checkout, the user would be able to choose Proton Blockchain as a payment option. Once chosen, they would see a list of allowed xTokens to pay with (as set by the admin settings), and be able to login using WebAuth. Once logged in, they would choose which token to pay with, with the order total automatically being accurately converted to the relevant currency. 
- Order statuses and order notes will automatically be updated for successful, failed or abandoned transactions. 

## Timeline

**PHASE ONE - WOO ADMIN: July 31st 2023**
Develop the Woocommerce admin settings page, including the ability to store relevant settings in a secure manner.

**PHASE TWO - CHECKOUT INTEGRATION: August 31st 2023**
Develop the frontend functionality for users to be able to checkout using WebAuth wallet, as well as the communication to update order statuses and notes for different transaction statuses. 

**PHASE THREE - TESTING & BUG FIXING: September 31st 2023**
Test the plugin in different environments and setups, and fix any bugs as necessary.

**Comment by paulgnz** [comment]
Thank you for your submission to take this project on, at this stage @SuperstrongBE was the first to claim this bounty and has made significant progress already.

**Comment by conorseed** [comment]
No worries. Thanks for considering the submission @paulgnz. All the best @SuperstrongBE. Shout out if you want a tester.

**Comment by SuperstrongBE** [comment]
Thank you @conorseed ! 
Yeah for sure, I need beta testers (we never have enough testers )!

**Comment by SuperstrongBE** [comment]
Just read your concept, and we have the same vision :)
