### ISSUE TITLE
Claim Discourse_plugin

### ISSUE THREAD

**Issue by conorseed** [ProtonProtocol/bounties#3]
# Claim for Bounty: Discourse Plugin for WebAuth Login

I would love to contribute working on this - as owner of Coruscate Digital and Lead Developer at Tailgunner, I have 10+ years experience developing websites. I also have great experience of Proton development being a frontend developer for FreeDAO - working on the [Freeos dApp](https://app.freeos.io/), as well as [The DAOScape](https://ezoku-2iaaa-aaaad-qdrqa-cai.ic.fleek.co/). I'm also slowly chipping away at a personal project: [ProtonPlay](https://protonplay.fun/).

## Concept

- An open source Discourse plugin where users can opt to log in using WebAuth.
- Users can also connect existing accounts to their WebAuth credentials.
- Users will still need to enter an email to associate with their accounts after authenticating for the first time. Once an email address is connected to the account, users can log in via WebAuth at any time.
- Admin will have the ability to the WebAuth plugin on/off

## Timeline

**PHASE ONE - ADMIN ✅**
Develop the plugin admin interface

**PHASE TWO - AUTHENTICATION INTEGRATION ✅**
Develop the frontend functionality for users to login via WebAuth. 
Develop the backend functionality to connect WebAuth credentials with accounts (new or existing). 

**PHASE THREE - TESTING & BUG FIXING ✅**
Test the plugin in different environments, setups and user scenarios. Fix any bugs as necessary. 

**PROTON CONSORTIUM REVIEW - IN PROGRESS**
Send the plugin to the consortium for review. Implement any feedback, and fix any bugs as necessary.

**Comment by conorseed** [comment]
### PHASE ONE - ADMIN  ✅
Admin side of the plugin developed, with the ability to turn WebAuth authentication on/off. From here, it's very straight forward to add in any extra plugin settings as required so I'd consider this done!

![admin](https://github.com/ProtonProtocol/bounties/assets/13262289/d5a3accf-441e-42d5-be6a-3858bd22dca1)

**Comment by paulgnz** [comment]
Thanks @conorseed You have officially claimed Discourse plugin!

**Comment by conorseed** [comment]
### PHASE TWO - Progress Update:

- Users can see "Log in with WebAuth" button when trying to login
- Users can see an option to "Connect" their exisiting account to WebAuth
- Clicking either of these buttons redirects to a page where users can log in using the Proton WebSDK

![login-01-login](https://github.com/ProtonProtocol/bounties/assets/13262289/cc0c3931-e543-4058-8ebc-aa722c4bfab5)

![login-01-connect](https://github.com/ProtonProtocol/bounties/assets/13262289/0e9ae84b-2a9a-4624-ad12-d778660ac7e6)


TO DO: 
- Develop the backend functionality to connect WebAuth credentials with accounts (new or existing)
- Finish the frontend and backend connection

**Comment by conorseed** [comment]
### PHASE TWO - Progress Update:

Users can now register an account via webauth: [View Screen Recording](https://github.com/ProtonProtocol/bounties/assets/13262289/998fd9d5-b919-41e3-b19e-8669c1df7fae)


Users can now connect an existing account to their webauth account: [View Screen Recording](https://github.com/ProtonProtocol/bounties/assets/13262289/873854ed-e9b2-478d-9db1-2245c57e33ee)

**TO DO**
Have the backend verify the webauth session to ensure the login is legit. At the moment, I'm thinking this is best way to verify:

- Have the backend generate a nonce and send to frontend
- Once the session has been created, require a transaction from the user which has the nonce in it
- Once the transaction has been signed, send the transaction ID, actor, permission and nonce to the backend
- Backend calls Proton API to verify the transaction exists on the chain, has the same actor and permission as the session, and contains the correct nonce. If so, allow login. If not, then something's not right so login fails.

**Comment by conorseed** [comment]
### PHASE TWO - Progress Update:

Backend verification now in full swing! It's all been tested and working on Testnet 🚀  [Checkout the video here.](https://github.com/ProtonProtocol/bounties/assets/13262289/68ecfcd0-2ca9-4254-b75b-2074b9c35327)


I've setup a very simple smart contract, which has a `verify` action and requires a string field called `nonce`. 
Here's how the whole process works:

1. User creates WebAuth session on frontend
2. Frontend requests nonce from backend. Backend creates nonce, assigns it to the Discourse Session, and sends it to the Frontend.
3. User then signs a transaction: Contract `discwebauth`, Action `verify`, withe the `nonce` from step 3 as data.
4. Frontend sends the Transaction ID from step 3, actor and permission from the WebAuth Session and the nonce to the backend.
5. Backend does a number of checks, returns with failed authentication if any of the checks don't pass:

- Check if the supplied nonce matches the nonce in the Discourse Session
- Makes sure there's a transaction ID to work with, as well as actor and permission strings
- Calls `get transaction` endpoint on the [Proton Dex API](https://api-docs.protondex.com/reference/historycontroller_gettransaction) to get the transaction details of the supplied transaction ID. 
- Checks the account and name of the transaction match `discwebauth` and `verify` respectively
- Checks the actor and permission of transaction matches the supplied actor and permission
- Checks the nonce field in the transaction data matches the supplied nonce
- Checks to make sure the transaction timestamp is no older than 60 seconds

6. Authentication passes!


**TO DO**

- Setup `discwebauth` account and contract on mainnet
- Test on mainnet
- Make strings easy to internationalise
- Tidy up code

**Comment by conorseed** [comment]
### PHASE TWO - AUTHENTICATION INTEGRATION  ✅

Completed the authentication flow for the plugin, on both Proton Testnet & Proton Mainnet. Basic testing complete on local machine. Code has been tidied up and commented through. Frontend is all setup for I18n if others want to contribute to expanding that side of things. 

**Next step: PHASE THREE - TESTING & BUG FIXING**
Test the plugin in different environments, setups and user scenarios. Fix any bugs as necessary.

**Comment by conorseed** [comment]
### PHASE THREE - Progress Update

![Screenshot 2023-07-27 at 5 09 58 PM](https://github.com/ProtonProtocol/bounties/assets/13262289/b8c9d52f-47d8-49f7-94b2-9c26d16c4612)

✅ Testing complete in local dev environment
✅ Testing completed on a Digital Ocean install of the latest Discourse version
⏳ Awaiting testing on a [Communiteq](https://www.communiteq.com/) setup to make sure it works in an alternative hosting environment

In the meantime, [here's the public repo for the plugin](https://github.com/conorseed/discourse-webauth) if anyone wants to test it themselves!

**Comment by conorseed** [comment]
### PHASE THREE - Progress Update

🐛 Found some mobile bugs and squashed them today, along with a potential timing issue around verifying the `verify` transaction via the Proton Dex API. Tested updates locally and on DigitalOcean install and all seems well. 

⏳ Testing is still on going for the [Communiteq](https://www.communiteq.com/) install, but even their support team think this is an awesome plugin... and well written!

![Screenshot 2023-07-28 at 9 26 13 AM](https://github.com/ProtonProtocol/bounties/assets/13262289/2fb65f8b-549c-46a2-aaee-a54e24b2c377)

**Comment by conorseed** [comment]
### PHASE THREE - TESTING & BUG FIXING ✅

✅ Local env testing complete
✅ Digital Ocean testing complete
✅ Communiteq testing complete

@paulgnz - here's the details you'll need to review:

Plugin Repo: https://github.com/conorseed/discourse-webauth
Video Walkthrough: https://vimeo.com/849268389/d2bb11f015

**Comment by marc0olo** [comment]
cool 😎 can't wait to see the forum!

@conorseed does the plugin handle the case where a username is already taken? could the team restrict the forum to allow webauth based authentication only? if this restriction can be done, could we make email an optional field in the registration?

background of the question:
- if email registration is activated, I could use a forum name of an existing Proton account and then block this account from having access to the forum if this scenario is not covered
- not everybody wants to provide their email (or just use a throwaway email anyway 😅)

**Comment by conorseed** [comment]
> @conorseed does the plugin handle the case where a username is already taken? 
> if email registration is activated, I could use a forum name of an existing Proton account and then block this account from having access to the forum if this scenario is not covered

@marc0olo - Yeah Discourse manages that already on registration: if the username exists as a Discourse account, it doesn't allow you to register with that username in Discourse. If registering via WebAuth, it will just put a number at the end to make it unique (I think). The webauth account and Discourse account names are independent of each other. So my Discourse username could be "hellothere", and it would be connected to my webauth account "generalkenobi". 


> could the team restrict the forum to allow webauth based authentication only? if this restriction can be done, could we make email an optional field in the registration?
> not everybody wants to provide their email (or just use a throwaway email anyway 😅)

That's a good question and a fair observation. I tried to make the plugin more universal, so it could slot in alongside other third party auth providers on existing Discourse installations. Plus it also means that users can receive the normal discourse emails around replies and the daily summaries etc...

For fresh installs this is probably a nice feature to have though. I'd need to look in to how possible it is to lock it all down to just WebAuth though!

**Comment by marc0olo** [comment]
> The webauth account and Discourse account names are independent of each other. So my Discourse username could be "hellothere", and it would be connected to my webauth account "generalkenobi".

totally fair and reasonable. in case of the "official" Proton forum I personally would love to have my nickname "reserved" for my Proton account. should maybe be a survey if people want to have the freedom to choose independent nicknames there 🤔 (cc @paulgnz)

> Plus it also means that users can receive the normal discourse emails around replies and the daily summaries etc...

true, but would be cool if it can be optional. if you regularly check the forum you anyway see notifications in the GUI 😉 

> For fresh installs this is probably a nice feature to have though. I'd need to look in to how possible it is to lock it all down to just WebAuth though!

yeah, my questions were mainly addressing fresh installs only 😅

**Comment by conorseed** [comment]
> yeah, my questions were mainly addressing fresh installs only 😅

Good to know! I'll look into it over the next day or so. It's likely more complicated than it appears 😉

> totally fair and reasonable. in case of the "official" Proton forum I personally would love to have my nickname "reserved" for my Proton account. should maybe be a survey if people want to have the freedom to choose independent nicknames there 🤔 (cc @paulgnz)

There's gonna be an official Proton forum? Cool 😎 Again, would need to look in to the name reservations though. Likely possible - but again probably more complicated than it appears due to how Discourse functions regularly! 

Would certainly be a nice feature for the official Proton forum though. I'm not sure if all these features are within the scope of this bounty, but more than happy to take a look once I've knocked out a couple of bugs @paulgnz found in testing on his end.
