### ISSUE TITLE
Claim NFT_faucet

### ISSUE THREAD

**Issue by SuperstrongBE** [ProtonProtocol/bounties#4]

**Comment by paulgnz** [comment]
Legend 🤘

**Comment by SuperstrongBE** [comment]
I'm going on! 

The advent calendar type of the Dapp is perfect for smart contract with one-time, on demand minting strategy. 
Also i have a lot of experience in interfacing Next App with XPRNetwork web sdk.

**Comment by Aaditya-T** [comment]
are you still working on this @SuperstrongBE? if not i would like to claim it 👀 
cc: @paulgnz

**Comment by SuperstrongBE** [comment]
Hello @Aaditya-T, 
Are you looking for the code ?
This bounty should be closed. cc: @paulgnz

**Comment by Aaditya-T** [comment]
ahh - i thought this bounty is incomplete 😅 it shows its still open thats on the open bounties page!

**Comment by SuperstrongBE** [comment]
Sorry :)
